export enum RoutePath {
    HOME = '/',
    LOGIN = '/login',
    LOGOUT = '/logout',
    SETTINGS_GAMES = '/gamessettings',
    SETTINGS_GAMES_ADD = 'gamessettings/add',
    SETTINGS_GAMES_EDIT = 'gamessettings/edit/:id',
    SETTINGS_GAMES_REMOVE = 'gamessettings/remove/:id',
    SETTINGS_GENRES = '/genressettings',
    SETTINGS_GENRES_ADD = 'genressettings/add',
    SETTINGS_GENRES_EDIT = 'genressettings/edit/:id',
    SETTINGS_GENRES_REMOVE = 'genressettings/remove/:id',
    SETTINGS_PROFILES = '/profilessettings',
    SETTINGS_PROFILES_ADD = 'profilessettings/add',
    SETTINGS_PROFILES_EDIT = 'profilessettings/edit/:id',
    SETTINGS_PROFILES_REMOVE = 'profilessettings/remove/:id',
  }